=== Oleksiy1984/EPAM-Training/SummaryTask3/input.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML schema -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://nure.ua/emelianov/SummaryTask3/entity"
	xmlns:tns="http://nure.ua/emelianov/SummaryTask3/entity">

	<xsd:element name="Device">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Part" type="tns:Part" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="Part">
		<xsd:sequence>
			<xsd:element name="Name" type="xsd:string" maxOccurs="1" />
			<xsd:element name="Origin" type="xsd:string" maxOccurs="1" />
			<xsd:element name="Price" type="xsd:integer" maxOccurs="1" />
			<xsd:element name="Type" type="tns:Type" maxOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="critical" type="xsd:boolean"
			default="false" />
	</xsd:complexType>

	<xsd:complexType name="Type">
		<xsd:sequence>
			<xsd:element name="Peripheral" type="xsd:boolean"
				maxOccurs="1" />
			<xsd:element name="EnergyConsumption" type="xsd:integer"
				maxOccurs="1" />
			<xsd:element name="CoolerAvailability" type="xsd:boolean"
				maxOccurs="1" />
			<xsd:element name="Group" type="xsd:string" maxOccurs="1" />
			<xsd:element name="Ports" type="tns:Ports" maxOccurs="1"></xsd:element>
		</xsd:sequence>

	</xsd:complexType>
	<xsd:complexType name="Ports">
		<xsd:sequence>
			<xsd:element name="COM" type="xsd:boolean" maxOccurs="1"></xsd:element>
			<xsd:element name="USB" type="xsd:boolean" maxOccurs="1"></xsd:element>
			<xsd:element name="LPT" type="xsd:boolean" maxOccurs="1"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

</xsd:schema>

=== Oleksiy1984/EPAM-Training/SummaryTask3/input.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Input XML document. This XML is valid against input.xsd XML schema -->

<st3:Device xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:st3="http://nure.ua/emelianov/SummaryTask3/entity"
	xsi:schemaLocation="http://nure.ua/emelianov/SummaryTask3/entity input.xsd">

	<Part critical="true">
		<Name>Device 1</Name>
		<Origin>Japan</Origin>
		<Price>200</Price>
		<Type>
			<Peripheral>false</Peripheral>
			<EnergyConsumption>500</EnergyConsumption>
			<CoolerAvailability>true</CoolerAvailability>
			<Group>Input</Group>
			<Ports>
				<COM>true</COM>
				<USB>true</USB>
				<LPT>true</LPT>
			</Ports>
		</Type>
	</Part>

	<Part critical="false">
		<Name>Device 2</Name>
		<Origin>China</Origin>
		<Price>100</Price>
		<Type>
			<Peripheral>true</Peripheral>
			<EnergyConsumption>300</EnergyConsumption>
			<CoolerAvailability>false</CoolerAvailability>
			<Group>Output</Group>
			<Ports>
				<COM>false</COM>
				<USB>true</USB>
				<LPT>false</LPT>
			</Ports>
		</Type>
	</Part>

	<Part critical="true">
		<Name>Device 3</Name>
		<Origin>Germany</Origin>
		<Price>300</Price>
		<Type>
			<Peripheral>false</Peripheral>
			<EnergyConsumption>400</EnergyConsumption>
			<CoolerAvailability>true</CoolerAvailability>
			<Group>Multimedia</Group>
			<Ports>
				<COM>true</COM>
				<USB>false</USB>
				<LPT>true</LPT>
			</Ports>
		</Type>
	</Part>
	
		<Part critical="false">
		<Name>Device 4</Name>
		<Origin>Italy</Origin>
		<Price>400</Price>
		<Type>
			<Peripheral>true</Peripheral>
			<EnergyConsumption>200</EnergyConsumption>
			<CoolerAvailability>false</CoolerAvailability>
			<Group>Input</Group>
			<Ports>
				<COM>false</COM>
				<USB>false</USB>
				<LPT>true</LPT>
			</Ports>
		</Type>
	</Part>

</st3:Device>
